s5e8825-common: Disable SLSI HWC Perf mode
This no longer compiles correctly:

hardware/samsung_slsi-linaro/graphics/base/libhwc2.1/device/ExynosDevice.cpp:39:10: fatal error: 'CpuPerfInfo.h' file not found
   39 | #include "CpuPerfInfo.h"
      |          ^~~~~~~~~~~~~~~
1 error generated.
21:49:21 ninja failed with: exit status 1

TODO: fix at source-level?

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>